version: '3.0'

networks:
  bitrix:

volumes:
  bitrix_db:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    environment:
      TZ: $TIME_ZONE
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html:delegated
      - ./log/access.log:/var/log/access.log
      - ./log/error.log:/var/log/error.log
    networks:
      bitrix:
        aliases:
          - $DOMAIN
    extra_hosts:
      - "${DOMAIN}:127.0.0.1"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: $TIME_ZONE
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES utf8;' --init-connect='SET collation_connection = "utf8_unicode_ci"' --sql_mode="" --innodb_strict_mode=0 --innodb-flush-log-at-trx-commit=0 --transaction-isolation=READ-COMMITTED --innodb_flush_method=O_DIRECT --innodb_file_per_table=1
    volumes:
      - bitrix_db:/var/lib/mysql
    networks:
      - bitrix

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    environment:
      TZ: $TIME_ZONE
    volumes:
      - ./www:/var/www/html:delegated
      - ./log/php.log:/var/log/php.log:delegated
    networks:
      - bitrix

  cron:
    build:
      context: .
      dockerfile: php.dockerfile
    environment:
      TZ: $TIME_ZONE
    volumes:
      - ./www:/var/www/html:delegated
      - ./log/cron.log:/var/log/cron.log
      - ./log/php.log:/var/log/php.log:delegated
    networks:
      - bitrix
    entrypoint: ["crond", "-f", "-l", "8"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      TZ: $TIME_ZONE
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - bitrix